# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(733, 745)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mainTabs = QtGui.QTabWidget(self.centralwidget)
        self.mainTabs.setObjectName(_fromUtf8("mainTabs"))
        self.searchTab = QtGui.QWidget()
        self.searchTab.setObjectName(_fromUtf8("searchTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.searchTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.modelGroupBox = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelGroupBox.sizePolicy().hasHeightForWidth())
        self.modelGroupBox.setSizePolicy(sizePolicy)
        self.modelGroupBox.setObjectName(_fromUtf8("modelGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.modelGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.modelGroupBox)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.vectorTab = QtGui.QWidget()
        self.vectorTab.setObjectName(_fromUtf8("vectorTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.vectorTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.vectorSearchLayout = QtGui.QHBoxLayout()
        self.vectorSearchLayout.setObjectName(_fromUtf8("vectorSearchLayout"))
        self.vectorSearchLineEdit = QtGui.QLineEdit(self.vectorTab)
        self.vectorSearchLineEdit.setObjectName(_fromUtf8("vectorSearchLineEdit"))
        self.vectorSearchLayout.addWidget(self.vectorSearchLineEdit)
        self.vectorSearchPushButton = QtGui.QPushButton(self.vectorTab)
        self.vectorSearchPushButton.setObjectName(_fromUtf8("vectorSearchPushButton"))
        self.vectorSearchLayout.addWidget(self.vectorSearchPushButton)
        self.verticalLayout_3.addLayout(self.vectorSearchLayout)
        self.vectorSimilarityGroupBox = QtGui.QGroupBox(self.vectorTab)
        self.vectorSimilarityGroupBox.setObjectName(_fromUtf8("vectorSimilarityGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.vectorSimilarityGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.innerProductRadioButton = QtGui.QRadioButton(self.vectorSimilarityGroupBox)
        self.innerProductRadioButton.setChecked(True)
        self.innerProductRadioButton.setObjectName(_fromUtf8("innerProductRadioButton"))
        self.horizontalLayout_2.addWidget(self.innerProductRadioButton)
        self.diceRadioButton = QtGui.QRadioButton(self.vectorSimilarityGroupBox)
        self.diceRadioButton.setObjectName(_fromUtf8("diceRadioButton"))
        self.horizontalLayout_2.addWidget(self.diceRadioButton)
        self.cosRadioButton = QtGui.QRadioButton(self.vectorSimilarityGroupBox)
        self.cosRadioButton.setObjectName(_fromUtf8("cosRadioButton"))
        self.horizontalLayout_2.addWidget(self.cosRadioButton)
        self.jaccardRadioButton = QtGui.QRadioButton(self.vectorSimilarityGroupBox)
        self.jaccardRadioButton.setObjectName(_fromUtf8("jaccardRadioButton"))
        self.horizontalLayout_2.addWidget(self.jaccardRadioButton)
        self.verticalLayout_3.addWidget(self.vectorSimilarityGroupBox)
        self.tabWidget.addTab(self.vectorTab, _fromUtf8(""))
        self.booleanTab = QtGui.QWidget()
        self.booleanTab.setObjectName(_fromUtf8("booleanTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.booleanTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.booleanSearchLayout = QtGui.QHBoxLayout()
        self.booleanSearchLayout.setObjectName(_fromUtf8("booleanSearchLayout"))
        self.booleanSearchLineEdit = QtGui.QLineEdit(self.booleanTab)
        self.booleanSearchLineEdit.setObjectName(_fromUtf8("booleanSearchLineEdit"))
        self.booleanSearchLayout.addWidget(self.booleanSearchLineEdit)
        self.booleanSearchPushButton = QtGui.QPushButton(self.booleanTab)
        self.booleanSearchPushButton.setObjectName(_fromUtf8("booleanSearchPushButton"))
        self.booleanSearchLayout.addWidget(self.booleanSearchPushButton)
        self.verticalLayout_4.addLayout(self.booleanSearchLayout)
        self.booleanNoteLabel = QtGui.QLabel(self.booleanTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booleanNoteLabel.sizePolicy().hasHeightForWidth())
        self.booleanNoteLabel.setSizePolicy(sizePolicy)
        self.booleanNoteLabel.setObjectName(_fromUtf8("booleanNoteLabel"))
        self.verticalLayout_4.addWidget(self.booleanNoteLabel)
        self.tabWidget.addTab(self.booleanTab, _fromUtf8(""))
        self.matchingScoreTab = QtGui.QWidget()
        self.matchingScoreTab.setObjectName(_fromUtf8("matchingScoreTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.matchingScoreTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.matchingScoreSearchLayout = QtGui.QHBoxLayout()
        self.matchingScoreSearchLayout.setObjectName(_fromUtf8("matchingScoreSearchLayout"))
        self.matchingScoreSearchLineEdit = QtGui.QLineEdit(self.matchingScoreTab)
        self.matchingScoreSearchLineEdit.setObjectName(_fromUtf8("matchingScoreSearchLineEdit"))
        self.matchingScoreSearchLayout.addWidget(self.matchingScoreSearchLineEdit)
        self.matchingScoreSearchPushButton = QtGui.QPushButton(self.matchingScoreTab)
        self.matchingScoreSearchPushButton.setObjectName(_fromUtf8("matchingScoreSearchPushButton"))
        self.matchingScoreSearchLayout.addWidget(self.matchingScoreSearchPushButton)
        self.verticalLayout_5.addLayout(self.matchingScoreSearchLayout)
        self.tabWidget.addTab(self.matchingScoreTab, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.modelGroupBox)
        self.ResultsGroupBox = QtGui.QGroupBox(self.searchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultsGroupBox.sizePolicy().hasHeightForWidth())
        self.ResultsGroupBox.setSizePolicy(sizePolicy)
        self.ResultsGroupBox.setObjectName(_fromUtf8("ResultsGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ResultsGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.resultsTableWidget = QtGui.QTableWidget(self.ResultsGroupBox)
        self.resultsTableWidget.setAutoFillBackground(False)
        self.resultsTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultsTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.resultsTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.resultsTableWidget.setObjectName(_fromUtf8("resultsTableWidget"))
        self.resultsTableWidget.setColumnCount(2)
        self.resultsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resultsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultsTableWidget.setHorizontalHeaderItem(1, item)
        self.resultsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.resultsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.resultsTableWidget)
        self.clearResultsPushButton = QtGui.QPushButton(self.ResultsGroupBox)
        self.clearResultsPushButton.setObjectName(_fromUtf8("clearResultsPushButton"))
        self.verticalLayout_2.addWidget(self.clearResultsPushButton)
        self.verticalLayout.addWidget(self.ResultsGroupBox)
        self.mainTabs.addTab(self.searchTab, _fromUtf8(""))
        self.inverseFileTab = QtGui.QWidget()
        self.inverseFileTab.setObjectName(_fromUtf8("inverseFileTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.inverseFileTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cacmDocumentsGroupBox = QtGui.QGroupBox(self.inverseFileTab)
        self.cacmDocumentsGroupBox.setObjectName(_fromUtf8("cacmDocumentsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.cacmDocumentsGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cacmAllFileLabel = QtGui.QLabel(self.cacmDocumentsGroupBox)
        self.cacmAllFileLabel.setObjectName(_fromUtf8("cacmAllFileLabel"))
        self.gridLayout.addWidget(self.cacmAllFileLabel, 0, 0, 1, 1)
        self.cacmAllFileLineEdit = QtGui.QLineEdit(self.cacmDocumentsGroupBox)
        self.cacmAllFileLineEdit.setObjectName(_fromUtf8("cacmAllFileLineEdit"))
        self.gridLayout.addWidget(self.cacmAllFileLineEdit, 0, 1, 1, 1)
        self.commonWordsFileLabel = QtGui.QLabel(self.cacmDocumentsGroupBox)
        self.commonWordsFileLabel.setObjectName(_fromUtf8("commonWordsFileLabel"))
        self.gridLayout.addWidget(self.commonWordsFileLabel, 1, 0, 1, 1)
        self.commonWordsFileLineEdit = QtGui.QLineEdit(self.cacmDocumentsGroupBox)
        self.commonWordsFileLineEdit.setObjectName(_fromUtf8("commonWordsFileLineEdit"))
        self.gridLayout.addWidget(self.commonWordsFileLineEdit, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.cacmDocumentsGroupBox)
        self.loadInverseFileGroupBox = QtGui.QGroupBox(self.inverseFileTab)
        self.loadInverseFileGroupBox.setObjectName(_fromUtf8("loadInverseFileGroupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.loadInverseFileGroupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.loadInverseFileLineEdit = QtGui.QLineEdit(self.loadInverseFileGroupBox)
        self.loadInverseFileLineEdit.setObjectName(_fromUtf8("loadInverseFileLineEdit"))
        self.horizontalLayout_5.addWidget(self.loadInverseFileLineEdit)
        self.loadInveseFilePushButton = QtGui.QPushButton(self.loadInverseFileGroupBox)
        self.loadInveseFilePushButton.setObjectName(_fromUtf8("loadInveseFilePushButton"))
        self.horizontalLayout_5.addWidget(self.loadInveseFilePushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.loadInverseFileSearchGroupBox = QtGui.QGroupBox(self.loadInverseFileGroupBox)
        self.loadInverseFileSearchGroupBox.setObjectName(_fromUtf8("loadInverseFileSearchGroupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.loadInverseFileSearchGroupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loadInverseFileSearchWordGroupBox = QtGui.QGroupBox(self.loadInverseFileSearchGroupBox)
        self.loadInverseFileSearchWordGroupBox.setObjectName(_fromUtf8("loadInverseFileSearchWordGroupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.loadInverseFileSearchWordGroupBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.loadInverseFileSearchWordLineEdit = QtGui.QLineEdit(self.loadInverseFileSearchWordGroupBox)
        self.loadInverseFileSearchWordLineEdit.setObjectName(_fromUtf8("loadInverseFileSearchWordLineEdit"))
        self.verticalLayout_8.addWidget(self.loadInverseFileSearchWordLineEdit)
        self.loadInverseFileSearchWordPushButton = QtGui.QPushButton(self.loadInverseFileSearchWordGroupBox)
        self.loadInverseFileSearchWordPushButton.setObjectName(_fromUtf8("loadInverseFileSearchWordPushButton"))
        self.verticalLayout_8.addWidget(self.loadInverseFileSearchWordPushButton)
        self.horizontalLayout_4.addWidget(self.loadInverseFileSearchWordGroupBox)
        self.loadInverseFileSearchDocumentGroupBox = QtGui.QGroupBox(self.loadInverseFileSearchGroupBox)
        self.loadInverseFileSearchDocumentGroupBox.setObjectName(_fromUtf8("loadInverseFileSearchDocumentGroupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.loadInverseFileSearchDocumentGroupBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.loadInverseFileSearchDocumentSpinBox = QtGui.QSpinBox(self.loadInverseFileSearchDocumentGroupBox)
        self.loadInverseFileSearchDocumentSpinBox.setMinimum(1)
        self.loadInverseFileSearchDocumentSpinBox.setMaximum(100)
        self.loadInverseFileSearchDocumentSpinBox.setObjectName(_fromUtf8("loadInverseFileSearchDocumentSpinBox"))
        self.verticalLayout_9.addWidget(self.loadInverseFileSearchDocumentSpinBox)
        self.loadInverseFileSearchDocumentPushButton = QtGui.QPushButton(self.loadInverseFileSearchDocumentGroupBox)
        self.loadInverseFileSearchDocumentPushButton.setObjectName(_fromUtf8("loadInverseFileSearchDocumentPushButton"))
        self.verticalLayout_9.addWidget(self.loadInverseFileSearchDocumentPushButton)
        self.horizontalLayout_4.addWidget(self.loadInverseFileSearchDocumentGroupBox)
        self.verticalLayout_10.addWidget(self.loadInverseFileSearchGroupBox)
        self.verticalLayout_6.addWidget(self.loadInverseFileGroupBox)
        self.saveInverseFileGroupBox = QtGui.QGroupBox(self.inverseFileTab)
        self.saveInverseFileGroupBox.setEnabled(True)
        self.saveInverseFileGroupBox.setObjectName(_fromUtf8("saveInverseFileGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.saveInverseFileGroupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.saveInverseFileFieldLayout = QtGui.QHBoxLayout()
        self.saveInverseFileFieldLayout.setObjectName(_fromUtf8("saveInverseFileFieldLayout"))
        self.saveInverseFileLineEdit = QtGui.QLineEdit(self.saveInverseFileGroupBox)
        self.saveInverseFileLineEdit.setObjectName(_fromUtf8("saveInverseFileLineEdit"))
        self.saveInverseFileFieldLayout.addWidget(self.saveInverseFileLineEdit)
        self.saveInveseFilePushButton = QtGui.QPushButton(self.saveInverseFileGroupBox)
        self.saveInveseFilePushButton.setObjectName(_fromUtf8("saveInveseFilePushButton"))
        self.saveInverseFileFieldLayout.addWidget(self.saveInveseFilePushButton)
        self.saveInverseFileGeneratePushButton = QtGui.QPushButton(self.saveInverseFileGroupBox)
        self.saveInverseFileGeneratePushButton.setObjectName(_fromUtf8("saveInverseFileGeneratePushButton"))
        self.saveInverseFileFieldLayout.addWidget(self.saveInverseFileGeneratePushButton)
        self.verticalLayout_7.addLayout(self.saveInverseFileFieldLayout)
        self.saveInverseFileFormulaGroupBox = QtGui.QGroupBox(self.saveInverseFileGroupBox)
        self.saveInverseFileFormulaGroupBox.setObjectName(_fromUtf8("saveInverseFileFormulaGroupBox"))
        self.saveInvefrseFileChoiceLayout = QtGui.QHBoxLayout(self.saveInverseFileFormulaGroupBox)
        self.saveInvefrseFileChoiceLayout.setObjectName(_fromUtf8("saveInvefrseFileChoiceLayout"))
        self.saveInverseFileTfIdfRadioButton = QtGui.QRadioButton(self.saveInverseFileFormulaGroupBox)
        self.saveInverseFileTfIdfRadioButton.setEnabled(True)
        self.saveInverseFileTfIdfRadioButton.setChecked(True)
        self.saveInverseFileTfIdfRadioButton.setObjectName(_fromUtf8("saveInverseFileTfIdfRadioButton"))
        self.saveInvefrseFileChoiceLayout.addWidget(self.saveInverseFileTfIdfRadioButton)
        self.saveInverseFileFrequencyRadioButton = QtGui.QRadioButton(self.saveInverseFileFormulaGroupBox)
        self.saveInverseFileFrequencyRadioButton.setChecked(False)
        self.saveInverseFileFrequencyRadioButton.setObjectName(_fromUtf8("saveInverseFileFrequencyRadioButton"))
        self.saveInvefrseFileChoiceLayout.addWidget(self.saveInverseFileFrequencyRadioButton)
        self.verticalLayout_7.addWidget(self.saveInverseFileFormulaGroupBox)
        self.verticalLayout_6.addWidget(self.saveInverseFileGroupBox)
        self.mainTabs.addTab(self.inverseFileTab, _fromUtf8(""))
        self.precisionRecalTab = QtGui.QWidget()
        self.precisionRecalTab.setObjectName(_fromUtf8("precisionRecalTab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.precisionRecalTab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.queryGroupBox = QtGui.QGroupBox(self.precisionRecalTab)
        self.queryGroupBox.setObjectName(_fromUtf8("queryGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.queryGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.queryFileLabel = QtGui.QLabel(self.queryGroupBox)
        self.queryFileLabel.setObjectName(_fromUtf8("queryFileLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.queryFileLabel)
        self.queryFileLineEdit = QtGui.QLineEdit(self.queryGroupBox)
        self.queryFileLineEdit.setObjectName(_fromUtf8("queryFileLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.queryFileLineEdit)
        self.qrelsFileLabel = QtGui.QLabel(self.queryGroupBox)
        self.qrelsFileLabel.setObjectName(_fromUtf8("qrelsFileLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.qrelsFileLabel)
        self.qrelsFileLineEdit = QtGui.QLineEdit(self.queryGroupBox)
        self.qrelsFileLineEdit.setObjectName(_fromUtf8("qrelsFileLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.qrelsFileLineEdit)
        self.precisionRecallGroupBox = QtGui.QGroupBox(self.queryGroupBox)
        self.precisionRecallGroupBox.setObjectName(_fromUtf8("precisionRecallGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.precisionRecallGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.innerProductLabel = QtGui.QLabel(self.precisionRecallGroupBox)
        self.innerProductLabel.setObjectName(_fromUtf8("innerProductLabel"))
        self.gridLayout_2.addWidget(self.innerProductLabel, 0, 0, 1, 1)
        self.innerProductPrecisionLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.innerProductPrecisionLineEdit.setReadOnly(True)
        self.innerProductPrecisionLineEdit.setObjectName(_fromUtf8("innerProductPrecisionLineEdit"))
        self.gridLayout_2.addWidget(self.innerProductPrecisionLineEdit, 0, 1, 1, 1)
        self.innerProductRecallLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.innerProductRecallLineEdit.setReadOnly(True)
        self.innerProductRecallLineEdit.setObjectName(_fromUtf8("innerProductRecallLineEdit"))
        self.gridLayout_2.addWidget(self.innerProductRecallLineEdit, 0, 2, 1, 1)
        self.diceLabel = QtGui.QLabel(self.precisionRecallGroupBox)
        self.diceLabel.setObjectName(_fromUtf8("diceLabel"))
        self.gridLayout_2.addWidget(self.diceLabel, 1, 0, 1, 1)
        self.dicePrecisionLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.dicePrecisionLineEdit.setReadOnly(True)
        self.dicePrecisionLineEdit.setObjectName(_fromUtf8("dicePrecisionLineEdit"))
        self.gridLayout_2.addWidget(self.dicePrecisionLineEdit, 1, 1, 1, 1)
        self.diceRecallLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.diceRecallLineEdit.setReadOnly(True)
        self.diceRecallLineEdit.setObjectName(_fromUtf8("diceRecallLineEdit"))
        self.gridLayout_2.addWidget(self.diceRecallLineEdit, 1, 2, 1, 1)
        self.cosLabel = QtGui.QLabel(self.precisionRecallGroupBox)
        self.cosLabel.setObjectName(_fromUtf8("cosLabel"))
        self.gridLayout_2.addWidget(self.cosLabel, 2, 0, 1, 1)
        self.cosPrecisionLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.cosPrecisionLineEdit.setReadOnly(True)
        self.cosPrecisionLineEdit.setObjectName(_fromUtf8("cosPrecisionLineEdit"))
        self.gridLayout_2.addWidget(self.cosPrecisionLineEdit, 2, 1, 1, 1)
        self.cosRecallLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.cosRecallLineEdit.setReadOnly(True)
        self.cosRecallLineEdit.setObjectName(_fromUtf8("cosRecallLineEdit"))
        self.gridLayout_2.addWidget(self.cosRecallLineEdit, 2, 2, 1, 1)
        self.jaccardLabel = QtGui.QLabel(self.precisionRecallGroupBox)
        self.jaccardLabel.setObjectName(_fromUtf8("jaccardLabel"))
        self.gridLayout_2.addWidget(self.jaccardLabel, 3, 0, 1, 1)
        self.jaccardPrecisionLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.jaccardPrecisionLineEdit.setReadOnly(True)
        self.jaccardPrecisionLineEdit.setObjectName(_fromUtf8("jaccardPrecisionLineEdit"))
        self.gridLayout_2.addWidget(self.jaccardPrecisionLineEdit, 3, 1, 1, 1)
        self.jaccardRecallLineEdit = QtGui.QLineEdit(self.precisionRecallGroupBox)
        self.jaccardRecallLineEdit.setReadOnly(True)
        self.jaccardRecallLineEdit.setObjectName(_fromUtf8("jaccardRecallLineEdit"))
        self.gridLayout_2.addWidget(self.jaccardRecallLineEdit, 3, 2, 1, 1)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.precisionRecallGroupBox)
        self.precisionRecallPushButton = QtGui.QPushButton(self.queryGroupBox)
        self.precisionRecallPushButton.setObjectName(_fromUtf8("precisionRecallPushButton"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.precisionRecallPushButton)
        self.verticalLayout_11.addWidget(self.queryGroupBox)
        self.mainTabs.addTab(self.precisionRecalTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.mainTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 37))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Recherche d\'informations - ABBAD & ZEBOUCHI", None))
        self.modelGroupBox.setTitle(_translate("MainWindow", "Modèle", None))
        self.vectorSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Votre requête", None))
        self.vectorSearchPushButton.setText(_translate("MainWindow", "Rechercher", None))
        self.vectorSimilarityGroupBox.setTitle(_translate("MainWindow", "Fonction de similarité", None))
        self.innerProductRadioButton.setText(_translate("MainWindow", "Produit interne", None))
        self.diceRadioButton.setText(_translate("MainWindow", "Dice", None))
        self.cosRadioButton.setText(_translate("MainWindow", "Cosinus", None))
        self.jaccardRadioButton.setText(_translate("MainWindow", "Jaccard", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vectorTab), _translate("MainWindow", "Vectoriel", None))
        self.booleanSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Votre requête", None))
        self.booleanSearchPushButton.setText(_translate("MainWindow", "Rechercher", None))
        self.booleanNoteLabel.setText(_translate("MainWindow", "<html><head/><body><p>Les opérateurs booléens : &amp; (et), | (ou), ~ (non).</p><p>Les parenthèses peuvent être utilisées pour indiquer la priorité.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.booleanTab), _translate("MainWindow", "Booléen", None))
        self.matchingScoreSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Votre requête", None))
        self.matchingScoreSearchPushButton.setText(_translate("MainWindow", "Rechercher", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.matchingScoreTab), _translate("MainWindow", "Matching score", None))
        self.ResultsGroupBox.setTitle(_translate("MainWindow", "Résultats", None))
        self.resultsTableWidget.setToolTip(_translate("MainWindow", "Double-click sur un document pour l\'ouvrir", None))
        self.resultsTableWidget.setSortingEnabled(True)
        item = self.resultsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Document", None))
        item = self.resultsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Score", None))
        self.clearResultsPushButton.setText(_translate("MainWindow", "Effacer les résultats", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.searchTab), _translate("MainWindow", "Recherche", None))
        self.cacmDocumentsGroupBox.setTitle(_translate("MainWindow", "Documents CACM", None))
        self.cacmAllFileLabel.setText(_translate("MainWindow", "Fichier <code>cacm.all</code>", None))
        self.cacmAllFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.commonWordsFileLabel.setText(_translate("MainWindow", "Fichier <code>common_words</code>", None))
        self.commonWordsFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.loadInverseFileGroupBox.setTitle(_translate("MainWindow", "Charger un fichier inverse", None))
        self.loadInverseFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.loadInveseFilePushButton.setText(_translate("MainWindow", "Sélectionner", None))
        self.loadInverseFileSearchGroupBox.setTitle(_translate("MainWindow", "Rechercher dans le fichier inverse", None))
        self.loadInverseFileSearchWordGroupBox.setTitle(_translate("MainWindow", "Par mot", None))
        self.loadInverseFileSearchWordPushButton.setText(_translate("MainWindow", "Rechercher", None))
        self.loadInverseFileSearchDocumentGroupBox.setTitle(_translate("MainWindow", "Par document", None))
        self.loadInverseFileSearchDocumentPushButton.setText(_translate("MainWindow", "Rechercher", None))
        self.saveInverseFileGroupBox.setTitle(_translate("MainWindow", "Sauvegarder un fichier inverse", None))
        self.saveInverseFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.saveInveseFilePushButton.setText(_translate("MainWindow", "Sélectionner", None))
        self.saveInverseFileGeneratePushButton.setText(_translate("MainWindow", "Générer", None))
        self.saveInverseFileFormulaGroupBox.setTitle(_translate("MainWindow", "Formule de pondération", None))
        self.saveInverseFileTfIdfRadioButton.setText(_translate("MainWindow", "Tf-Idf", None))
        self.saveInverseFileFrequencyRadioButton.setText(_translate("MainWindow", "Fréquence simple", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.inverseFileTab), _translate("MainWindow", "Documents et fichier inverse", None))
        self.queryGroupBox.setTitle(_translate("MainWindow", "Fichiers de test", None))
        self.queryFileLabel.setText(_translate("MainWindow", "Fichier <code>query.text</code>", None))
        self.queryFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.qrelsFileLabel.setText(_translate("MainWindow", "Fichier <code>qrels.text</code>", None))
        self.qrelsFileLineEdit.setPlaceholderText(_translate("MainWindow", "Chemin du fichier", None))
        self.precisionRecallGroupBox.setTitle(_translate("MainWindow", "Précision et rappel", None))
        self.innerProductLabel.setText(_translate("MainWindow", "Produit interne", None))
        self.diceLabel.setText(_translate("MainWindow", "Dice", None))
        self.cosLabel.setText(_translate("MainWindow", "Cosinus", None))
        self.jaccardLabel.setText(_translate("MainWindow", "Jaccard", None))
        self.precisionRecallPushButton.setText(_translate("MainWindow", "Lancer les testes", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.precisionRecalTab), _translate("MainWindow", "Précision et rappel", None))

